### PR TITLE
Broken ws

### LINKED ISSUE #76: Signer: It takes 4 seconds to see unauthorized page in extension.
It should be faster (the response is already there)

### PR DESCRIPTION
**Pull request by goldylucks**
- contains #79
- resolves #76, #75, #65 
- fixes broken WS responses introduced in ethcore/parity#1665

### CODE REVIEW

File: components/src/TransactionPendingFormConfirm/TransactionPendingFormConfirm.js [hunk 1]
```diff
@@ -43,6 +44,7 @@ export default class TransactionPendingFormConfirm extends Component {
             className={ styles.confirmButton }
             fullWidth
             primary
+            disabled={ this.props.isSending }
             label='Confirm Transaction'
```
Comment (tomusdrw) [inline components/src/TransactionPendingFormConfirm/TransactionPendingFormConfirm.js]: Maybe label could change when it's being sent?

File: signer/web/src/middlewares/ws.js [hunk 2]
```diff
@@ -33,56 +33,32 @@ export default class LocalstorageMiddleware {
...
-      if (res === undefined) {
-        transaction.status = 'rejected';
-        transaction.error = true;
-        transaction.msg = 'Not enough funds.';
-        store.dispatch(addErrorTransaction(transaction));
-        return next(action);
+    this.send('personal_confirmTransaction', [ id, {}, password ], (err, txHash) => {
+      logger.log('[WS MIDDLEWARE] confirm transaction cb:', err, txHash);
+      if (err) {
+        store.dispatch(actions.errorConfirmTransaction({ id, err: err.message }));
```
Comment (tomusdrw) [inline signer/web/src/middlewares/ws.js:42]: ~~for debugging it might be usefull to print whole error object to console~~ NVM, just spoted log above.

File: signer/web/src/reducers/transactions.js [hunk 3]
```diff
@@ -15,33 +15,80 @@ export default handleActions({
...
+      ...state,
+      pending
+    };
+  },
 
+  'success confirmTransaction' (state, action) {
+    const { id, txHash } = action.payload;
+    const confirmed = Object.assign({},
+      state.pending.find(p => p.id === id),
+      { txHash }, { status: 'confirmed' }
```
Comment (tomusdrw) [inline signer/web/src/reducers/transactions.js]: Why not:

``` javascript
const confirmed = Object.assign(state.pending.find(...), { status: 'confirmed', txHash })
```

?

File: signer/web/src/reducers/transactions.js [hunk 4]
```diff
@@ -15,33 +15,80 @@ export default handleActions({
...
+      return p;
+    });
+    return {
+      ...state,
+      pending
+    };
+  },
 
+  'start rejectTransaction' (state, action) {
+    const pending = state.pending.map(p => {
```
Comment (tomusdrw) [inline signer/web/src/reducers/transactions.js]: Maybe it would be better to store transactions in a `Map/Object` instead of an array?

File: components/src/TransactionPendingFormConfirm/TransactionPendingFormConfirm.js (hunk 1 above)
Comment (goldylucks) [inline components/src/TransactionPendingFormConfirm/TransactionPendingFormConfirm.js]: it happens very fast, would just flicker (not cool)

we might wanna handle long responses in a separate pr, like if waiting time over 1-2 seconds, reflect sending state in UI

File: signer/web/src/reducers/transactions.js (hunk 3 above)
Comment (goldylucks) [inline signer/web/src/reducers/transactions.js]: 1. <del>`state.pending.find(...)` would mutate the state
   in this specific case we override it anyway, tho I don't feel safe doing that</del>
   nvm, we use the spread operator anywayz
2. `{ status: 'confirmed', txHash }` :+1:

File: signer/web/src/reducers/transactions.js (hunk 4 above)
Comment (goldylucks) [inline signer/web/src/reducers/transactions.js]: yes I thought about that as well when refactoring, tho they were implemented as array,
so I might do that in a separate PR

Comment (tomusdrw) [inline signer/web/src/reducers/transactions.js]: Why not in this one? Right now `find`/`filter` code looks a bit ugly - would be nicer to have some abstraction or to rewrite to object. (You can actually store both: object and array)

File: components/src/TransactionPendingFormConfirm/TransactionPendingFormConfirm.js (hunk 1 above)
Comment (tomusdrw) [inline components/src/TransactionPendingFormConfirm/TransactionPendingFormConfirm.js]: k

**Comment by tomusdrw** [comment]
All good, except for the updating transaction ugliness. Would be nice to have it in some function or to refactor it into object.

File: signer/web/src/reducers/transactions.js (hunk 4 above)
Comment (goldylucks) [inline signer/web/src/reducers/transactions.js]: initially I didn't want to abstract since this part is kinda prone to change.
abstracted start/error actions for now

File: signer/web/src/providers/appProvider.js [hunk 5]
```diff
@@ -14,14 +14,19 @@ export default class appProvider {
...
-      .then(isRunning => {
-        this.store.dispatch(updateAppState({ isParityRunning: isRunning, isLoading: false, isWsConnected: false }));
-      });
+    this.store.dispatch(
+      updateAppState({ isLoading: false, isWsConnected: false })
+    );
+    // isParityRunning(this.wsPath)
+    //   .then(isRunning => {
+    //     this.store.dispatch(updateAppState({ isParityRunning: isRunning, isLoading: false, isWsConnected: false }));
+    //   });
```
Comment (rphmeier) [inline signer/web/src/providers/appProvider.js]: lot of commented out code in this file

Comment (goldylucks) [inline signer/web/src/providers/appProvider.js]: yup
will b gone soon enough:)
